//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcResult
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int urunID { get; set; }
        public string urunAdi { get; set; }
        public int urunFiyati { get; set; }
        public int musteriID { get; set; }
    
        public virtual musteri musteri { get; set; }
    }
}
